# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestELEARNPORTAL():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_eLEARNPORTAL(self):
        self.driver = webdriver.Chrome(executable_path="D:\MTECH-BITS-PILANI\seleniumautomation\drivers\chromedriver_win32\chromedriver.exe")
        self.vars = {}
        self.driver.get("https://elearn.bits-pilani.ac.in/")
        self.driver.set_window_size(1616, 886)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "username").click()
        self.driver.find_element(By.ID, "username").send_keys("2020mt93149@wilp.bits-pilani.ac.in")
        self.driver.find_element(By.ID, "pass").click()
        self.driver.find_element(By.ID, "pass").send_keys("******")
        self.driver.find_element(By.ID, "submitbtn").click()
        self.driver.find_element(By.LINK_TEXT, "My Courses").click()
        self.driver.execute_script("window.scrollTo(0,2)")
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, "#heading6534 .btn").click()
        self.vars["win4869"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win4869"])
        self.driver.find_element(By.CSS_SELECTOR, "#module-128339 .instancename").click()
        self.driver.find_element(By.CSS_SELECTOR, ".no-overflow").click()
        time.sleep(10)
        self.driver.close()

c=TestELEARNPORTAL()
c.test_eLEARNPORTAL()